# Generated by Django 5.0.6 on 2024-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_crudmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudmodel',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crudmodel',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crudmodel',
            name='delivery',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crudmodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
