# Generated by Django 5.0.6 on 2024-07-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_clientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
